### ISSUE TITLE
Get bats tests working.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/ddev-backdrop-bee#1]
This addon seems to work in reality, but it does not work according to the bats tests. I have changed very little about the bats tests from the original addon template. All I did was change the `health_checks()` section, as follows:

Original:
```
health_checks() {
  # Do something useful here that verifies the add-on
  # ddev exec "curl -s elasticsearch:9200" | grep "${PROJNAME}-elasticsearch"
  ddev exec "curl -s https://localhost:443/"
}
```
Replacement for ddev-backdrop-bee:
```
health_checks() {
  # Do something useful here that verifies the add-on
  ddev restart
  ddev bee status
}
```

This seems to fail both with and without  `ddev restart`, I'm not sure if that is necessary.

**Comment by tyler36** [comment]
Hi @jenlampton 

Look like the "install from directory" is passing 

```
170 ok 1 install from directory
```

But the "install from release" is not

```
172 not ok 2 install from release
```

The release tests require a GitHub release which I see you have `0.0.0`. Not sure if you have tried rerunning the tests after the release. Is `0.0.0` considered a valid release number?

Checkout "https://github.com/ddev/ddev-addon-template/pull/58" if you need a "workaround".

**Comment by tyler36** [comment]
And as @rfay pointed out, and beat me to it, you'll need to fix which is currently pointing to the template repo.

```diff
-  echo "# ddev get ddev/ddev-addon-template with project ${PROJNAME} in ${TESTDIR} ($(pwd))" >&3
-  ddev get ddev/ddev-addon-template
+  echo "# ddev get jenlampton/ddev-backdrop-bee with project ${PROJNAME} in ${TESTDIR} ($(pwd))" >&3
+  ddev get get jenlampton/ddev-backdrop-bee
```

**Comment by jenlampton** [comment]
> Not sure if you have tried rerunning the tests after the release.

I had, that's why I numbered it 0.0.0 -- because I wasn't sure it would work yet :) 

> currently pointing to the template repo.

I think when I tried to "undo" all my changes, I also undid the find/replace 🤦
