### ISSUE TITLE
Add `ddev-get` to make addon discoverable

### ISSUE THREAD

**Issue by tyler36** [backdrop-ops/ddev-backdrop-bee#2]
Thank you for creating the addon.
I know many people in the bee community will be happy.

To get the addon to display in `ddev addon list --all`, you need to add a topic.

On the homepage, on the right side:

![image](https://github.com/user-attachments/assets/098fb0f6-18d8-47de-829f-fc35c8831d0e)

Add `ddev-get`

![image](https://github.com/user-attachments/assets/0ecdd4b9-cb3b-47c7-89da-142278a748d3)

You then see it appear in: `ddev addon list --all`

**Comment by jenlampton** [comment]
Done! thank you.

**Comment by tyler36** [comment]
Confirmed.

## Test

```shell
$ ddev get --list --all | grep bee
│ jenlampton/ddev-backdrop-bee                      │ Install bee for Backdrop sites on ddev.            │
```

Thank you!
