### ISSUE TITLE
When you've happy with it you'll probably want to move to backdrop org

### ISSUE THREAD

**Issue by rfay** [backdrop-ops/ddev-backdrop-bee#4]
When you are happy with this, you may want to promote/move it to the backdrop org, where it will have a clearer home.

**Comment by stasadev** [comment]
Small suggestions:

- [docker-compose.backdrop-bee.yaml](https://github.com/jenlampton/ddev-backdrop-bee/blob/main/docker-compose.backdrop-bee.yaml) is not needed here, if `bee` is added only to the web image.
- [`bee`](https://github.com/jenlampton/ddev-backdrop-bee/blob/main/commands/web/bee) should have `#ddev-generated` with annotations (that will be used for `ddev help bee` https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#annotations-supported), for example:

    ```bash
    #!/bin/bash
    #ddev-generated
    ## Description: Run command line utility for Backdrop CMS
    ## Usage: bee
    ## Example: ddev bee

    /usr/local/bin/bee/bee.php --root=/var/www/html/$DDEV_DOCROOT --uri=$DDEV_PRIMARY_URL $@
    ```

**Comment by jenlampton** [comment]
> When you are happy with this, you may want to promote/move it to the backdrop org, where it will have a clearer home.

I was waiting to hear from one of the other contributors before I moved it, but it has now been moved to https://github.com/backdrop-ops/ddev-backdrop-bee

> [docker-compose.backdrop-bee.yaml](https://github.com/jenlampton/ddev-backdrop-bee/blob/main/docker-compose.backdrop-bee.yaml) is not needed here, if bee is added only to the web image.

Removed. I wondered about that, I only added it since it was in the documentation for the addons.

> [bee](https://github.com/jenlampton/ddev-backdrop-bee/blob/main/commands/web/bee) should have #ddev-generated with annotations

Added. Thank you!

**Comment by stasadev** [comment]
> bee should have #ddev-generated with annotations

I don't know why, but GitHub added an extra space for each line:

https://github.com/backdrop-ops/ddev-backdrop-bee/blob/b4522055b103adbdc32e1aa562b338723161f61e/commands/web/bee#L1-L5

And simple copy-paste was not enough here 🙂

You can remove those extra spaces and test if it's really working with:

```
ddev help bee
```

**Comment by stasadev** [comment]
Now I checked it myself, and I see `bee` is a global command:

https://github.com/backdrop-ops/ddev-backdrop-bee/blob/b4522055b103adbdc32e1aa562b338723161f61e/install.yaml#L61-L67

This means that anyone who uses this add-on needs to manually run `ddev get backdrop-ops/ddev-backdrop-bee` to make the command available for them (or each repository that uses `ddev bee` should have a hook that runs this `ddev get`).

I think `commands/web/bee` should be moved to the `project_files`, and then add-on users will be able to commit everything inside `.ddev` to git and `ddev bee` will be available for them without pulling this add-on again.

---

I guess we need to include `commands` example to `project_files`, this is probably the only reason you added it to the `global_files`:

https://github.com/ddev/ddev-addon-template/blob/3e29bb5559941cea6bf40b2903846c6b9a490643/install.yaml#L70-L71

**Comment by jenlampton** [comment]
>  guess we need to include commands example to project_files, this is probably the only reason you added it to the global_files:

Yep, I had it locally initially because I was setting it up locally for each site (before the addon) -- but when I saw the example where it was in global, I switched it. 

I've switched it back :)

(AND I tested with `ddev get https://github.com/backdrop-ops/ddev-backdrop-bee/tarball/main`!)
