### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/ddev-backdrop-bee#5]
With the message `Unable to expand files and directories: stat docker-compose.backdrop-bee.yaml: no such file or directory `

This is because we removed the file, but not the command that copied the file. Change on the way.

**Comment by stasadev** [comment]
FYI, add-ons can be tested locally or from HEAD or from PRs, like this:

```
ddev get /path/to/add-on
ddev get https://github.com/backdrop-ops/ddev-backdrop-bee/tarball/main
ddev get https://github.com/backdrop-ops/ddev-backdrop-bee/tarball/branch_name_here
```

This error could be detected more quickly without making a release.

**Comment by jenlampton** [comment]
Thanks, that's useful! I'd been making releases to test `ddev get` and crossing my fingers!
